  #section 1
  version: '3.8'

  #section 2 - each service one container
  services:
    
    smartledger-api: #service name
    
      build: . #build image from docker file in the current folder 
      container_name: smartledger-api
      ports:
        - "8080:80"
      environment:
         #framework setting - production , development , staging
        - ASPNETCORE_ENVIRONMENT=Production

        #"ConnectionStrings":"Default" - from appsetings (: = _ _)
        - ConnectionStrings__Default=Server=sql-server,1433;Database=SmartLedgerDb;User=sa;Password=PASSWORD@1a;TrustServerCertificate=true
  
        #secrets - keys etc (never actual sectrest - comes from .env or secret manager)
                 #~~~~ FROM APPSETTINGS.JSON ~~~~~ (: = _ _)
        - Jwt__Key=${JWT_KEY}  #from .env
        - Jwt__Issuer=SmartLedgerAPI #same
        - Jwt__Audience=SmartLedgerUsers #same
        - AISettings__ApiKey=${AI_KEY} #from .env
        - AISettings__AIModel=llama-3.1-8b-instant #same
      
      volumes:
        - ./logs:/app/Logs

      depends_on:
        - sql-server #startup order
 
      networks:
        - app-network #connects container to app defined at bottom

      restart: unless-stopped

  #service 2
    sql-server:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: smartledger-sqlserver
      ports:
         - "1433:1433"
      environment:
          ACCEPT_EULA: "Y" #END USER LICENSE AGREEMENT
          SA_PASSWORD: "PASSWORD@1a"  #SYSTEM ADMINISTRATOR PASSWORD
      volumes:
         - sqlserver-data:/var/opt/mssql
      networks:
         - app-network
      restart: unless-stopped

#service 3 ...
 
  volumes:  #list of all named volumes
    sqlserver-data:

  networks:
    app-network:
       driver: bridge
  
  